name: Update Resource Schema
env:
  SOURCE_REPO: pulumi/pulumi-aws
  USERNAME: ${{ github.actor }}
  PATH_SOURCE_CHECKOUT: upstream_pulumi_aws_repo
  PATH_OUR_REPO_CHECKOUT: our_codegen_repo
  TARGET_FILE: "provider/cmd/pulumi-resource-aws/schema.json"

on: 
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  UpdateSchemaFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pulumi/pulumi-aws repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}

      - name: Check if the AWS schema file was changed
        run: |
          cd $PATH_SOURCE_CHECKOUT
          if [[ $(git log --since='1 day ago' ${{ env.TARGET_FILE }} | wc -w) -gt 0 ]]; then
            echo 'We have changes' 
            echo "MergeChanges=true" >> $GITHUB_ENV
          else
            echo 'We have no changes'
          fi
          cd ..

      - name: Checkout Our Codegen repo 
        if: env.MergeChanges == 'true'
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_OUR_REPO_CHECKOUT }}
          
      - name: Update AWS schema file
        if: env.MergeChanges == 'true'
        run: |
          cp $PATH_SOURCE_CHECKOUT/$TARGET_FILE $PATH_OUR_REPO_CHECKOUT/resourceSchema/schema_aws.json
          cd $PATH_OUR_REPO_CHECKOUT
          git add .
          if [[ $(git diff --staged --name-only|wc -l) -gt 0 ]]; then
            echo "We do have changes between the copies, we are committing the changes"
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git commit -m "Updated AWS Schema file"
            git push -f origin main
          else
            echo "We have no changes between the copies, exiting"
          fi
          cd ..
          
